FROM python:3.11-slim

RUN apt-get update \
&& apt-get -y install libpq-dev gcc postgresql-client \
&& rm -rf /var/lib/apt/lists

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pip install pipenv && \
    pipenv install --deploy --system --ignore-pipfile && \
    pipenv install --dev --deploy --system --ignore-pipfile

COPY . .

ENTRYPOINT [ "pipenv", "run", "tox" ]