repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: ''
    hooks:
    -   id: flake8
        exclude: ^tests
-   repo: https://github.com/PyCQA/isort
    rev: ''
    hooks:
    -   id: isort